export interface Features {
    id: string,
    url: string,
    ratio_digits_host_var: number,
    abnormal_subdomain_var: number,
    nb_external_redirection_var: number,
    avg_word_host_var: number,
    tld_in_subdomain_var: number,
    longest_word_host_var: number,
    tld_in_path_var: number,
    ratio_digits_url_var: number,
    ip_var: number,
    nb_underscore_var: number,
    http_in_path_var: number,
    shortest_word_host_var: number,
    length_hostname_var: number,
    nb_dots_var: number,
    avg_words_raw_var: number,
    length_words_raw_var: number,
    nb_eq_var: number,
    nb_semicolumn_var: number,
    nb_and_var: number,
    phish_hints_var: number,
    nb_hyperlinks_var: number,
    status_var: number
}
